### ISSUE TITLE
Mi primer Issues

### ISSUE THREAD

**Issue by davidmolinafernadez** [curso-github-cefire/sesion3-practica#391]

**Comment by davidmolinafernadez** [comment]
Hola

**Comment by pedroprieto** [comment]
Buenas! Para la práctica tienes que crear el issue en tu repositorio, no en el mío.

Un saludo!!

**Comment by davidmolinafernadez** [comment]
Disculpame Pedro,


________________________________
De: Pedro Prieto ***@***.***>
Enviado: lunes, 22 de enero de 2024 11:14
Para: curso-github-cefire/sesion3-practica ***@***.***>
Cc: MOLINA FERNANDEZ, DAVID ***@***.***>; Author ***@***.***>
Asunto: Re: [curso-github-cefire/sesion3-practica] Mi primer Issues (Issue #391)


Buenas! Para la práctica tienes que crear el issue en tu repositorio, no en el mío.

Un saludo!!

**Comment by pedroprieto** [comment]
Sin problema :relaxed: Para eso estamos :wink:
